### PR TITLE
Small feature additions to tracer and to logger

### PR DESCRIPTION
**Pull request by byte-sculptor**
Really small features that I've had to add to Tracer and to Logger. Basically, when after each optimization run, I want to have an EvaluationReport that contains the tracer events, and all the log records (along with goodness of fit metrics over time etc.). I also want to be able to pickle/unpickle them and to dump them to files. 

Furthermore, the evaluation uses multiprocessing, so capturing the PID in the Traces helps disambiguate events from different runs and render them pretty.

Tracer:
* we capture thread id and PID with traced events

Logger:
* we save the record as is, instead of turning it into a dictionary. This is a minor perf improvement, but it also allows us to use the formatter specified by the user when dumping records to file.
* we can dump traces to file now.

### CODE REVIEW

**Comment by bpkroth** [comment]
Just to be clear, this is initial work to capture some additional execution context trace to file that we can later on upload to some sort of github actions archive to help with unit test failure analysis.  However, it's not actually invoking the dump_to_file, nor the archive save yet, correct?

**Comment by byte-sculptor** [comment]
> Just to be clear, this is initial work to capture some additional execution context trace to file that we can later on upload to some sort of github actions archive to help with unit test failure analysis. However, it's not actually invoking the dump_to_file, nor the archive save yet, correct?

Correct, this functionality would be used both by the scenario you describe (to help debug test failures) and by optimizer evaluation tools. And yes - the dump_to_file is not invoked anywhere.

**Comment by bpkroth** [comment]
> 
> 
> > Just to be clear, this is initial work to capture some additional execution context trace to file that we can later on upload to some sort of github actions archive to help with unit test failure analysis. However, it's not actually invoking the dump_to_file, nor the archive save yet, correct?
> 
> Correct, this functionality would be used both by the scenario you describe (to help debug test failures) and by optimizer evaluation tools. And yes - the dump_to_file is not invoked anywhere.

Thanks.  I was looking it over before there was a description :)

**Review by bpkroth — APPROVED** [review]
LGTM

**Pull request merged**
