### PR TITLE
Policheck Fixes

### PR DESCRIPTION
**Pull request by byte-sculptor**

### CODE REVIEW

**Review by bpkroth — APPROVED** [review]
LGTM

**Review by sergiy-k — APPROVED** [review]

**Comment by bpkroth** [comment]
For the record, we seem to be hitting some sort of Github cache actions infrastructure issue atm: https://github.com/actions/cache/issues/544

**Review by bpkroth — CHANGES_REQUESTED** [review]
@byte-sculptor, we should drop this one now and take the version from #225.

**Comment by byte-sculptor** [comment]
> @byte-sculptor, we should drop this one now and take the version from #225.

Agreed

**Pull request closed without merging**
